#set_from_resource	  $color15_i3wmthemer	    color15
#set_from_resource	  $color14_i3wmthemer	    color14
#set_from_resource	  $color13_i3wmthemer	    color13
#set_from_resource	  $color12_i3wmthemer	    color12
#set_from_resource	  $color11_i3wmthemer	    color11
#set_from_resource	  $color10_i3wmthemer	    color10
#set_from_resource	  $color09_i3wmthemer		  color9
#set_from_resource	  $color08_i3wmthemer		  color8
#set_from_resource	  $color07_i3wmthemer		  color7
#set_from_resource 	$color06_i3wmthemer		  color6
#set_from_resource 	$color05_i3wmthemer 	    color5
#set_from_resource 	$color04_i3wmthemer 	    color4
#set_from_resource 	$color03_i3wmthemer 	    color3
#set_from_resource 	$color02_i3wmthemer 	    color2
#set_from_resource 	$color01_i3wmthemer 	    color1
#set_from_resource	  $color00_i3wmthemer		  color0
#set_from_resource	  $foreground_i3wmthemer	foreground
#set_from_resource	  $background_i3wmthemer	background

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.

#font pango:monospace 8
font xft:Hack 10

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal
#bindsym $mod+Return exec terminology
#bindsym $mod+Return exec x-terminal-emulator
#bindsym $mod+Return exec termite

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
#bindsym $mod+d exec dmenu_run
#bindsym $mod+d exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -dmenu'
bindsym $mod+d exec --no-startup-id rofi -show run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
#scratchpad
#bindsym $mod+Shift+z move scratchpad
#bindsym $mod+z scratchpad show
#bindsym $mod+o [title="^Sup ::"] scratchpad show

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

#::::::::::::::::::::::: Customize workspace name :::::::::::::::::::::::::::::#

#set $WS1   1:  Bash
#set $WS2   2:  Web
#set $WS3   3:  File
#set $WS4   4:  Code
#set $WS5   5:  Media
#set $WS6   6:  Chat
#set $WS7   7:  Doc
#set $WS8   "8:  eMail"
#set $WS9   9:  Conf
#set $WS0   10:  Games

#assign [class="Thunderbird"] workspace 8
#assign [class="thunderbird"] → workspace 8

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10
bindsym $mod+Tab workspace next
bindsym $mod+Shift+Tab workspace prev

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# Set shut down, restart and locking features
bindsym $mod+p mode "$mode_system"
set $mode_system (l)ock, (e)xit, switch_(u)ser, (s)uspend, (h)ibernate, (r)eboot, (Shift+s)hutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id i3exit lock, mode "default"
    bindsym s exec --no-startup-id i3exit suspend, mode "default"
    bindsym u exec --no-startup-id i3exit switch_user, mode "default"
    bindsym e exec --no-startup-id i3exit logout, mode "default"
    bindsym h exec --no-startup-id i3exit hibernate, mode "default"
    bindsym r exec --no-startup-id i3exit reboot, mode "default"
    bindsym Shift+s exec --no-startup-id i3exit shutdown, mode "default"

    # exit system mode: "Enter" or "Escape"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
#bar {
#        status_command i3status
#}

# Audio
# Pulse Audio controls
#bindsym XF86AudioRaiseVolume exec "amixer -c 0 set PCM 5dB+"
#volume
#bindsym XF86AudioLowerVolume exec "amixer -c 0 set PCM 5dB-"
#volume
#
bindsym XF86AudioRaiseVolume exec amixer -q set Master  4%+ unmute 
bindsym XF86AudioLowerVolume exec amixer -q set Master  4%- unmute
#
#bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5%
#bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5%
bindsym XF86AudioMute exec amixer -q set Master toggle
# Sreen brightness controls
bindsym XF86MonBrightnessUp exec xbright +20
bindsym XF86MonBrightnessDown exec xbright -20

# Wallpaper
exec --no-startup-id feh --bg-scale /home/omar/Pictures/rick_morty.jpg
# Conky
exec --no-startup-id conky -c ~/.conky.conf

#polybar
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
#exec_always pkill -9 polybar ; polybar top
#wifi
exec --no-startup-id nm-applet
#print screen
#bindsym Print exec "scrot -e 'mv $f ~/screenshots/'"
#bindsym Shift+Print exec "scrot -de 'mv $f ~/screenshots/'"
#bindsym $mod+Print exec "scrot -ue 'mv $f ~/screenshots/'"

bindsym Print exec "flameshot gui -p ~/screenshots/

#bindsym $mod+Print exec "flameshot full -p  ~/screenshots/"

#           Minimizar ventanas
# Mover ventana al scratchpad
bindsym $mod+Shift+minus move scratchpad

# # Mostrar scratchpad
bindsym $mod+minus scratchpad show

#aplicacions
#bindsym $mod+g exec firefox-beta
#bindsym $mod+t exec telegram-desktop
bindsym $mod+n exec x-terminal-emulator -e ranger
#bindsym $mod+n exec termite -e ranger
bindsym $mod+shift+n exec nautilus 
bindsym $mod+shift+Return exec tdrop -a x-terminal-emulator
bindsym $mod+m exec tdrop -a nautilus

#lock
bindsym $mod+x exec i3lock-fancy
#exec --no-startup-id compton -f
#exec --no-startup-id compton 
exec --no-startup-id compton --config ~/.compton.conf
exec --no-startup-id redshift-gtk
#exec --no-startup-id flameshot

#conectar pantalla
#bindsym $mod+shift+m exec arandr
bindsym XF86Display exec arandr

#Launch xfce4-appfinder
bindsym XF86Tools exec xfce4-appfinder

#natural scrolling and tab
exec xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
exec xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 
exec xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Scrolling Distance" "-112" "-112"

#Dropbox
#exec --no-startup-id dropbox start

#/execbluetooth
#exec --no-startup-id /usr/bin/blueman-applet                 # Bluetooth Manager

#:::::::::::::::::::::::::::::::: i3 Panel ::::::::::::::::::::::::::::::::::::#

#bar {
#  status_command i3status
#  font pango:Hack, FontAwesome 10
#}

#:::::::::::::::::::::: Config del panel ::::::::::::::::::::::#
################################################################
#bar {
##	id 			bar-1
##	status_command 		i3blocks -c ~/.config/i3/i3blocks.conf
#	status_command i3status
#       strip_workspace_numbers yes
#	position 		top
#	mode 			dock
#	workspace_buttons 	yes
##	tray_output 		eDP1
#  	height 			25
#	font 			pango: ohsnap, awesome 12
##	separator_symbol 	"::"


#colors {
#		background #005f87 #0088aa
#		statusline #000000
#		separator  #FF9955
##		background $transparent
##
##
##::::::::::::::::::::::: Indicadores ::::::::::::::::::::::::::#
#################################################################
##				    border backgr. text
#		focused_workspace  #FF9955 #FF9955 #222222
#		inactive_workspace #0087af #0087af #DFDFDF
#		urgent_workspace   #ef5350 #ef5350 #DFDFDF
#	}

#}
################################################################

#::::::::::::::::::::::::::::: Frame window :::::::::::::::::::::::::::::::::::#

# Class                      border  backgr   text  indicator child_border
client.focused		 	#171f27 #171f27 #ffffff  #ffffff   #171f27
client.focused_inactive 	#1d2121 #1d2121 #a1a1a1  #484e50   #1d2121
client.unfocused        	#333333 #222222 #888888  #292d2e   #222222
client.urgent   		#4a4b4c #4a4b4c #fdfdfd  #fbfbfb   #4a4c4b
client.placeholder      	#000000 #0c0c0c #ffffff  #000000   #0c0c0c

client.background           #111111


#:::::::::::::::::::::::: Settings for gaps window ::::::::::::::::::::::::::::#

# Set inner/outer gapsset $default_gaps_inner 8
#set $default_gaps_outer -4
#gaps inner $default_gaps_inner
#gaps outer $default_gaps_outer

#smart_gaps on
#smart_borders on

# Press $mod+Shift+g to enter the gap mode. Choose o or i for modifying
# outer/inner gaps. Press one of + / - (in-/decrement for current workspace) or
# 0 (remove gaps for current workspace). If you also press Shift with these
# keys, the change will be global for all workspaces.

set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)
bindsym $mod+Shift+g mode "$mode_gaps"

mode "$mode_gaps" {
    bindsym o       mode "$mode_gaps_outer"
    bindsym i       mode "$mode_gaps_inner"
    bindsym Return  mode "default"
    bindsym Escape  mode "default"
}

mode "$mode_gaps_inner" {
    bindsym plus    gaps inner current plus 3
    bindsym minus   gaps inner current minus 3
    bindsym 0       gaps inner current set 0

    bindsym Shift+plus  gaps inner all plus 3
    bindsym Shift+minus gaps inner all minus 3
    bindsym Shift+0     gaps inner all set 0

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

mode "$mode_gaps_outer" {
    bindsym plus    gaps outer current plus 3
    bindsym minus   gaps outer current minus 3
    bindsym 0       gaps outer current set 0

    bindsym Shift+plus  gaps outer all plus 3
    bindsym Shift+minus gaps outer all minus 3
    bindsym Shift+0     gaps outer all set 0

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

#       Media player control key
#bindsym $mod+Ctrl+up exec "mpc toggle"
#bindsym $mod+Ctrl+down exec "mpc stop"
#bindsym $mod+Ctrl+Left exec "mpc prev"
#bindsym $mod+Ctrl+Right exec "mpc next"


#       Call web browser
#bindsym $mod+F1 exec chromium #palemoon

#       Call file manager
#bindsym $mod+F2 exec nautilus

#       Conky
#exec conky -d; sleep 1 && transset-df .5 -n Conky &

#		Xresources
exec --no-startup-id xrdb ~/.Xresources

#		Dunst
exec --no-startup-id dunst -config ~/.config/dunst/dunstrc

# 	Xresources, xmodmap, start urxvt daemon
exec --no-startup-id "/usr/bin/xmodmap /home/<user>/.keymap"
exec --no-startup-id "/usr/bin/urxvtd -q -f -o"
exec --no-startup-id setxkbmap -layout gb,es
bindsym $mod+F1 exec setxkbmap -layout gb
bindsym $mod+F2 exec setxkbmap -layout es

exec --no-startup-id "source ~/.bashrc"

exec --no-startup-id i3-msg 'workspace 10; exec thunderbird'
#exec --no-startup-id i3-msg 'workspace 9; exec spotify'
exec --no-startup-id i3-msg 'workspace 1; exec firefox'
